### PR TITLE
Feature/142/implement sign up

### LINKED ISSUE #142: Implement sign-up
### Context

Our front-end has the UI for creating a new account, however the sign-up button doesn't do anything. The backend also supports authentication right now, but the two have not been connected yet.

### TODO

- [ ] On the "Sign Up" page when the "Sign Up" button is clicked, create a new user with the information contained in the sign-up form (i.e. "Username" and "Password").

### Notes

The endpoint you want to hit when creating a new user is `register_user` at "/login/users/register". The generated client in the frontend (found in `frontend/src/_generated/api/services/LoginService.ts`) has a function called `registerUser`; this function will make the API call necessary.

### LINKED ISSUE #146: Modify companies with scraping config
## Context

All of our scraping configurations are defined in the `data/companies` folder in JSON files. Each company has its own scraping config (which we have defined [here](https://github.com/johndpjr/AgTern/wiki/Web-Scraping)). Some companies have a `scrape: null` key-value mapping; this means that we have not defined a scraping config for that company's job board yet, but are planning to.

## TODO

- [x] Read the [scraping config definition](https://github.com/johndpjr/AgTern/wiki/Web-Scraping)
- [x] Look at companies that already have a complete scraping config and get a feel for how it works
- [x] Understand the [Document Object Model (DOM)](https://www.w3.org/TR/WD-DOM/introduction.html) and what [XPath](https://www.w3schools.com/xml/xpath_syntax.asp) is
- [x] Look at a specific company configuration, go to the `link` property, open [Chrome dev tools](https://developer.chrome.com/docs/devtools/open/), and use [the Chrome element inspector debugger](https://developer.chrome.com/docs/devtools/dom/) to look at the scraping properties and what is being scraped (i.e. look at the `xpath` property and match it with the web element/text /header that you see on the company job board in your web browser)

## Notes

### PR DESCRIPTION
**Pull request by johndpjr**
Closes #142  

- Fully implements a sign in page: users can now sign up with a username, email, and password
- Adds appropriate validation to username, email, and password (form cannot be submitted w/o it passing)
- Redirects to the jobs page on successful sign up

### CODE REVIEW

**Review by Jwdegames — COMMENTED** [review]
Sign up works but duplicate users can be signed up. May need to check database for that?

**Comment by johndpjr** [comment]
Thanks for letting me know - I fixed the issue. The backend logic wouldn't allow the duplicate usernames anyway, but it is much better practice to let the user know - so I handled the HTTP 400 error in the frontend and displayed the appropriate error.

**Comment by Jwdegames** [comment]
Confirmed that can't signup duplicate users

**Comment by Jwdegames** [comment]
Accidentally closed it instead of approving it.

**Comment by Jwdegames** [comment]
Should be good to approve - tested locally.

**Review by Jwdegames — APPROVED** [review]
Code works locally. Can sign up and am also prohibited from duplicate usernames.

**Pull request merged**
